# Generated by Django 5.0.2 on 2024-02-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quotes.author"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(to="quotes.tag"),
        ),
    ]
