# Generated by Django 5.0.2 on 2024-02-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_alter_quote_author_alter_quote_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.DateField(default="2024-02-02"),
        ),
    ]
