# Generated by Django 5.0.2 on 2024-02-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_author_email_alter_author_born_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="email",
        ),
    ]
